# Generated by Django 4.0 on 2022-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('paid', 'Paid'), ('shipper', 'Shipper'), ('refunded', 'Refunded'), ('patrial-refunded', 'Patrial Refunded')], default='processing', max_length=80, null=True),
        ),
    ]
