# Generated by Django 4.0 on 2022-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory_order',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('patrial-refunded', 'Patrial Refunded')], default='Processing', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('patrial-refunded', 'Patrial Refunded')], default='Processing', max_length=80, null=True),
        ),
    ]
