# Generated by Django 4.0 on 2022-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_accessory_order_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory_order',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('patrial-refund', 'Patrial Refund')], default='Processing', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('patrial-refund', 'Patrial Refund')], default='Processing', max_length=80, null=True),
        ),
    ]
