# Generated by Django 4.0 on 2022-01-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_vehicle_colour'),
        ('checkout', '0013_alter_accessory_order_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_line_item',
            new_name='vehicle_order_line_item',
        ),
    ]
