# Generated by Django 4.0 on 2021-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=9)),
                ('registration', models.CharField(max_length=254)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('trim', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=20)),
                ('engine_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('body_type', models.CharField(max_length=15)),
                ('gearbox', models.CharField(max_length=15)),
                ('drivetrain', models.CharField(max_length=10)),
                ('seats', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('mileage', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
