# Generated by Django 4.0 on 2021-12-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=254)),
                ('registration', models.CharField(max_length=254)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('trim', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=20)),
                ('engine_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('body_type', models.CharField(max_length=15)),
                ('gearbox', models.CharField(max_length=15)),
                ('drivetrain', models.CharField(max_length=10)),
                ('seats', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('doors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('vehicle_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
