# Generated by Django 4.0 on 2021-12-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available',
            field=models.CharField(default='yes', max_length=9),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='vehicle', max_length=9),
        ),
    ]
