# Generated by Django 4.0 on 2021-12-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleimages_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='full_price',
            field=models.IntegerField(default=200),
        ),
    ]
