# Generated by Django 4.0 on 2022-01-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='full_price',
            field=models.IntegerField(),
        ),
    ]
