# Generated by Django 4.0 on 2022-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_engine_size_alter_vehicle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('4x4', '4x4'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('estate', 'Estate'), ('hatchback', 'Hatchback'), ('motorhome', 'Motorhome'), ('mpv', 'MPV'), ('pickup', 'Pickup'), ('saloon', 'Saloon'), ('suv', 'SUV'), ('van', 'Van')], max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('green', 'Green'), ('multi-coloured', 'Multi-Coloured'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('white', 'White'), ('yellow', 'Yellow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(choices=[('2wd', '2WD'), ('4wd', '4WD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('petrol-hybrid', 'Petrol-Hybrid'), ('diesel-hybrid', 'Diesel-Hybrid'), ('hydrogen', 'Hydrogen'), ('electricity', 'Electricity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic')], max_length=15),
        ),
    ]
