# Generated by Django 4.0 on 2022-01-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_body_type_alter_vehicle_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimages',
            name='image',
            field=models.ImageField(null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicleimages',
            name='main',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleimages',
            name='vehicle_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
