# Generated by Django 4.0 on 2022-01-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_vehicleimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=9),
        ),
    ]
