# Generated by Django 4.0 on 2022-01-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_alter_vehicle_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimages',
            options={'verbose_name_plural': 'Vehicle Images'},
        ),
    ]
