# Generated by Django 4.0 on 2022-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_vehicleimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('green', 'Green'), ('grey', 'Grey'), ('multi-coloured', 'Multi-Coloured'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('white', 'White'), ('yellow', 'Yellow')], max_length=50),
        ),
    ]
