# Generated by Django 4.0 on 2022-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_vehicle_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('4x4', '4x4'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('estate', 'Estate'), ('hatchback', 'Hatchback'), ('motorhome', 'Motorhome'), ('mpv', 'MPV'), ('pickup', 'Pickup'), ('saloon', 'Saloon'), ('suv', 'SUV'), ('van', 'Van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('green', 'Green'), ('grey', 'Grey'), ('multi-coloured', 'Multi-Coloured'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('white', 'White'), ('yellow', 'Yellow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], max_length=20),
        ),
    ]
