# Generated by Django 4.0 on 2022-01-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='vehicle', max_length=15),
        ),
    ]
