# Generated by Django 4.0 on 2022-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_accessoryorder_accessoryorderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryorderlineitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
