# Generated by Django 4.0 on 2022-01-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_alter_category_options_alter_category_image'),
        ('profiles', '0002_alter_userprofile_default_phone_number'),
        ('vehicles', '0013_alter_vehicle_colour'),
        ('checkout', '0010_alter_order_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessoryOrder',
            new_name='accessory_order',
        ),
        migrations.RenameModel(
            old_name='AccessoryOrderLineItem',
            new_name='accessory_order_line_item',
        ),
        migrations.RenameModel(
            old_name='OrderLineItem',
            new_name='order_line_item',
        ),
    ]
