# Generated by Django 4.0 on 2022-01-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_default_phone_number'),
        ('checkout', '0011_rename_accessoryorder_accessory_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory_order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_orders', to='profiles.userprofile'),
        ),
    ]
